---
name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2, 8.3, 8.4]

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with: { bun-version: latest }

      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, curl, gd, intl, mbstring
        env:
          fail-fast: true

      - name: Cache NPM packages
        uses: actions/cache@v4
        env:
          cache-name: npm
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Cache Composer packages
        uses: actions/cache@v4
        env:
          cache-name: composer
        with:
          path: vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: Install NPM packages
        run: bun install --frozen-lockfile

      - name: Install Composer packages
        run: composer install

      - name: Check code format
        run: bun run-script format-check

      - name: Check code format
        run: composer run-script analyze

      - name: Scan for malware
        run: composer run-script scan-malware

      - name: Run tests
        run: composer run-script test
